apiVersion: v1
kind: Service
metadata:
  name: kube-weather
  namespace: ngrok-operator
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: kube-weather
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-weather
  namespace: ngrok-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-weather
  template:
    metadata:
      labels:
        app: kube-weather
    spec:
      containers:
        - name: backend
          image: alexwhen/docker-2048
          ports:
            - name: http
              containerPort: 80
---
# highlight-start
# ngrok Kubernetes Operator Configuration
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-weather-ingress
  namespace: ngrok-operator
spec:
  ingressClassName: ngrok
  rules:
    - host: vigorously-superb-python.ngrok-free.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-weather
                port:
                  number: 80
# highlight-end